### ISSUE TITLE
useMutabilityObject does not work anymore

### ISSUE THREAD

**Issue by vytch** [icyJoseph/useElementResize#6]
Hi, 

I have been using this hook last year.
It seems that the useMutabilityObject hook does not work anymore.
I have tried also the example and it does not work either.

To reproduce the issue, in the index.js:
- remove the useDetectElementResize so we only useMutabilityObserver.
- Then resize the window horizontally so the width changes. We can see the width indicator does not update.

In the demo, adding extra items does updates the height indicator, that's because children has been added, the mutationObserver detects it and calls the callback.
However element resizing, without altering the tree does not seem to be detecting anything.

**Comment by icyJoseph** [comment]
Oh, I had missed this on a mountain of emails.

Yeah, unfortunately, the Mutation Observer, only executes its callbacks when there's DOM changes, like for example, text changes, etc.

A very simple trick here, is to implement a resize observer, and expose that, while also making sure that `useMutabilityObserver` uses it under the hood (though I also export that hook). 

This way, `useMutabilityObserver` won't just catch width/height changes because of DOM interactions, but actual viewport changes.
